# Rosé Pine theme
# background #191724
background_opacity 0.5
# foreground #b8c4d9

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
# cursor #e0def4
# selection_background #403d52
# selection_foreground #e0def4

# black
# color0  #26233a
# color8  #6e6a86

# red
# color1  #eb6f92
# color9  #eb6f92

# green
# color2  #31748f
# color10 #31748f

# yellow
# color3  #f6c177
# color11 #f6c177

# blue
# color4  #9ccfd8
# color12 #9ccfd8

# magenta
# color5  #c4a7e7
# color13 #c4a7e7

# cyan
# color6  #ebbcba
# color14 #ebbcba

# white
# color7  #e0def4
# color15 #e0def4

# Fonts
font_family      Iosevka Nerd Font
bold_font        Iosevka Nerd Font Bold
italic_font      Iosevka Nerd Font Italic
bold_italic_font Iosevka Nerd Font Bold Italic
font_size 12.0

# Keybinds
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+f5 load_config_file
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0


# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME