# Centre monitor
wallpaper {
     monitor = DP-2
     path = ~/Downloads/ROG_circuit_waves_1920x1080.png
     fit_mode = cover
}

# Left monitor
wallpaper {
     monitor = HDMI-A-1
     path = ~/Downloads/MSI-rgb.png
     fit_mode = cover
}

# Right monitor
wallpaper {
    monitor = DP-1
    path = ~/Downloads/asus-strix.jpg
    fit_mode = cover
  }
